version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 732716521491.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building backend image...
      - docker build -t backend ./backend
      - docker tag backend:latest 732716521491.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      - echo Building frontend image...
      - docker build -t frontend ./frontend
      - docker tag frontend:latest 732716521491.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
  post_build:
    commands:
      - echo Pushing backend image...
      - docker push 732716521491.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      - echo Pushing frontend image...
      - docker push 732716521491.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
